use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Embed the existing WebGUI assets into the binary so a single executable is enough.
fn main() {
    let web_root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/network_manager/web");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let generated = out_dir.join("web_assets.rs");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    collect(&web_root, &web_root, &mut entries);
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut source = String::new();
    source.push_str("// Generated by build.rs - do not edit.\n");
    source.push_str("pub struct Asset {\n    pub path: &'static str,\n    pub content: &'static [u8],\n}\n\n");
    source.push_str("pub const ASSETS: &[Asset] = &[\n");
    for (relative, absolute) in &entries {
        let escaped = absolute.to_string_lossy().replace('\\', "\\\\");
        source.push_str("    Asset {\n");
        source.push_str(&format!("        path: \"{}\",\n", relative));
        source.push_str(&format!(
            "        content: include_bytes!(\"{escaped}\"),\n"
        ));
        source.push_str("    },\n");
    }
    source.push_str("];\n");

    fs::write(&generated, source).expect("write generated assets");
    println!("cargo:rerun-if-changed={}", web_root.display());

    // Windows 上把图标、UAC 提权清单嵌进 exe：
    //   - 图标让安装后在资源管理器/开始菜单里显示应用图标；
    //   - requireAdministrator 是 TUN 虚拟网卡的前提，Python 版靠 PyInstaller
    //     的 uac_admin=True 实现，这里必须等价，否则 mihomo 会报
    //     "configure tun interface: Access is denied"。
    #[cfg(target_os = "windows")]
    {
        let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets");
        let icon = web_root.join("icons").join("network-manager.ico");
        let manifest = assets.join("app.manifest");

        let mut rc = String::new();
        if icon.exists() {
            let escaped = icon.to_string_lossy().replace('\\', "\\\\");
            rc.push_str(&format!("1 ICON \"{escaped}\"\n"));
            println!("cargo:rerun-if-changed={}", icon.display());
        }
        if manifest.exists() {
            let escaped = manifest.to_string_lossy().replace('\\', "\\\\");
            // 24 = RT_MANIFEST，1 = 资源 ID（可执行文件的主清单）。
            rc.push_str(&format!("1 24 \"{escaped}\"\n"));
            println!("cargo:rerun-if-changed={}", manifest.display());
        }

        if !rc.is_empty() {
            let rc_path = out_dir.join("app_resources.rc");
            fs::write(&rc_path, rc).expect("write resource rc");
            embed_resource::compile(&rc_path, embed_resource::NONE)
                .manifest_required()
                .expect("embed windows resources");
        }
    }
}

fn collect(root: &Path, current: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(current) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let Ok(relative) = path.strip_prefix(root) else {
                continue;
            };
            let relative = relative.to_string_lossy().replace('\\', "/");
            out.push((relative, path));
        }
    }
}
